#!/usr/bin/env python
import curses, argparse
from include.userinterface import UserInterface

def draw_ui(stdscr):
    curses.start_color()
    curses.init_pair(1, curses.COLOR_RED, curses.COLOR_BLACK)
    curses.init_pair(2, curses.COLOR_GREEN, curses.COLOR_BLACK)
    curses.init_pair(3, curses.COLOR_BLUE, curses.COLOR_BLACK)
    stdscr.clear()
    UI = UserInterface(stdscr)
    UI.render()

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Dashboard Interface")
    args = parser.parse_args()
    curses.wrapper(lambda stdscr: draw_ui(stdscr))
